### ISSUE TITLE
Error: [Workflow Telemetry] Unable to finish stat collector

### ISSUE THREAD

**Issue by kalverra** [catchpoint/workflow-telemetry-action#63]
[Here](https://github.com/smartcontractkit/chainlink/actions/runs/8177584349?pr=12313) is the run where I see this issue. The step and process trace post fine (mostly) but nothing else is showing. Logs have:

```
Error: [Workflow Telemetry] Unable to finish stat collector
Error: [Workflow Telemetry] AggregateError
Error: AggregateError
```

I'm suspecting 2 different sources for this issue:

## Action Fails

The action I'm trying to monitor fails with: `Process completed with exit code 137` which seems to be GitHub Actions code for `you used too many resources` (thus me wanting to integrate telemetry).

## Perimssions

We have a fairly locked-down environment, and I'm wondering if it's a permissions issue. We're running with these permissions:

```yaml
  permissions:
    actions: read
    checks: write
    pull-requests: write
    id-token: write
    contents: read
```
