### ISSUE TITLE
Process trace not displaying

### ISSUE THREAD

**Issue by HugoJP1** [catchpoint/workflow-telemetry-action#79]
Hi I have added this action with the following configuration:
```
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          theme: "dark"
          comment_on_pr: "false"
          proc_trace_chart_max_count: 50
```

And the job executes well and displays in the workflow summary. However the process trace doesn't display at all:

![image](https://github.com/user-attachments/assets/810eac29-f290-4717-879a-dc717ba3f0e0)

Any ideas on what I can try to fix? I have already tried setting a lower `proc_trace_chart_max_count`, but with no difference in result.
